/**
 * Recipe Detail Block
 * Comprehensive recipe page layout inspired by Vitamix.com recipe pages
 * Content generated by AI with structured recipe information
 */

/**
 * Decorate the recipe-detail block
 * @param {Element} block - The block element
 */
export default function decorate(block) {
  block.classList.add('recipe-detail');

  // Check if block is already rendered by page-renderer (has recipe-hero child)
  // Skip re-rendering to avoid flash
  if (block.querySelector('.recipe-hero')) {
    // Already rendered - just setup event handlers
    setupRelatedRecipeLinks(block);
    setupTabs(block);
    return;
  }

  // Get recipe data from block's dataset (populated by renderer)
  const data = block.dataset.recipe ? JSON.parse(block.dataset.recipe) : null;

  if (!data) {
    block.innerHTML = '<p class="error">Recipe data not available</p>';
    return;
  }

  // Check if image URL is a prompt (needs generation) or actual URL
  const imageUrl = data.image_url || '';
  const hasImage = imageUrl.startsWith('http') || imageUrl.startsWith('/');

  // Build the recipe detail layout
  const html = `
    <div class="recipe-hero">
      <div class="recipe-hero-inner">
        <div class="recipe-image ${hasImage ? '' : 'skeleton'}">
          ${hasImage ? `<img src="${imageUrl}" alt="${data.name}" loading="eager">` : ''}
        </div>
        <div class="recipe-header">
          <h1 class="recipe-title">${data.name}</h1>

          <div class="recipe-rating">
            <span class="stars">★★★★☆</span>
            <span class="rating-count">(${data.review_count || 0})</span>
            <span class="write-review">Write a review</span>
          </div>

          ${data.description ? `<p class="recipe-description">${data.description}</p>` : ''}

          <div class="recipe-meta">
            ${data.total_time ? `
              <div class="meta-item">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                  <circle cx="12" cy="12" r="10"></circle>
                  <polyline points="12 6 12 12 16 14"></polyline>
                </svg>
                <span class="meta-label">Total Time</span>
                <span class="meta-value">${data.total_time}</span>
              </div>
            ` : ''}
            ${data.servings ? `
              <div class="meta-item">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                  <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                  <circle cx="9" cy="7" r="4"></circle>
                  <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                  <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                </svg>
                <span class="meta-label">Yield</span>
                <span class="meta-value">${data.servings}</span>
              </div>
            ` : ''}
            ${data.difficulty ? `
              <div class="meta-item">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                  <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
                </svg>
                <span class="meta-label">Difficulty</span>
                <span class="meta-value">${data.difficulty}</span>
              </div>
            ` : ''}
          </div>

          ${data.tags && data.tags.length > 0 ? `
            <div class="recipe-dietary-tags">
              ${data.tags.slice(0, 4).map((tag) => `<span class="dietary-tag">${tag}</span>`).join('')}
            </div>
          ` : ''}
        </div>
      </div>
    </div>

    <div class="recipe-content-wrapper">
      <div class="recipe-tabs">
        <span class="recipe-tab active">The Recipe</span>
        <span class="recipe-tab">Nutritional Facts</span>
        <span class="recipe-tab">Reviews</span>
      </div>

      <div class="recipe-content">
        <div class="recipe-sidebar">
          <div class="sidebar-actions">
            <button class="sidebar-action">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path>
              </svg>
              Save
            </button>
            <button class="sidebar-action">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <polyline points="6 9 6 2 18 2 18 9"></polyline>
                <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"></path>
                <rect x="6" y="14" width="12" height="8"></rect>
              </svg>
              Print
            </button>
            <button class="sidebar-action">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <circle cx="18" cy="5" r="3"></circle>
                <circle cx="6" cy="12" r="3"></circle>
                <circle cx="18" cy="19" r="3"></circle>
                <line x1="8.59" y1="13.51" x2="15.42" y2="17.49"></line>
                <line x1="15.41" y1="6.51" x2="8.59" y2="10.49"></line>
              </svg>
              Share
            </button>
          </div>

          ${data.equipment && data.equipment.length > 0 ? `
            <div class="container-selector">
              <div class="container-selector-label">Refine Your Recipe</div>
              <div class="container-selector-value">
                Container Size
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <polyline points="6 9 12 15 18 9"></polyline>
                </svg>
              </div>
            </div>
          ` : ''}

          ${data.nutrition ? `
            <div class="nutrition-card">
              <h3>Nutrition</h3>
              <p class="serving-info">${data.nutrition.serving_size || '1 serving'}</p>
              <div class="nutrition-list">
                ${data.nutrition.calories ? `
                  <div class="nutrition-row primary">
                    <span class="nutrition-label">Calories</span>
                    <span class="nutrition-value">${data.nutrition.calories}</span>
                  </div>
                ` : ''}
                ${data.nutrition.fat ? `
                  <div class="nutrition-row">
                    <span class="nutrition-label">Total Fat</span>
                    <span class="nutrition-value">${data.nutrition.fat}</span>
                  </div>
                ` : ''}
                ${data.nutrition.carbs ? `
                  <div class="nutrition-row">
                    <span class="nutrition-label">Total Carbohydrate</span>
                    <span class="nutrition-value">${data.nutrition.carbs}</span>
                  </div>
                ` : ''}
                ${data.nutrition.fiber ? `
                  <div class="nutrition-row">
                    <span class="nutrition-label">Dietary Fiber</span>
                    <span class="nutrition-value">${data.nutrition.fiber}</span>
                  </div>
                ` : ''}
                ${data.nutrition.sugar ? `
                  <div class="nutrition-row">
                    <span class="nutrition-label">Sugars</span>
                    <span class="nutrition-value">${data.nutrition.sugar}</span>
                  </div>
                ` : ''}
                ${data.nutrition.protein ? `
                  <div class="nutrition-row">
                    <span class="nutrition-label">Protein</span>
                    <span class="nutrition-value">${data.nutrition.protein}</span>
                  </div>
                ` : ''}
              </div>
            </div>
          ` : ''}

          ${data.equipment && data.equipment.length > 0 ? `
            <div class="equipment-card">
              <h3>Equipment Needed</h3>
              <ul>
                ${data.equipment.map((item) => `<li>${item}</li>`).join('')}
              </ul>
            </div>
          ` : ''}

          ${data.tags && data.tags.length > 0 ? `
            <div class="tags-card">
              <h3>Tags</h3>
              <div class="tags-list">
                ${data.tags.map((tag) => `<span class="tag">${tag}</span>`).join('')}
              </div>
            </div>
          ` : ''}
        </div>

        <div class="recipe-main">
          ${data.ingredients && data.ingredients.length > 0 ? `
            <div class="recipe-section ingredients-section">
              <div class="ingredients-header">
                <h2>Ingredients</h2>
                <div class="unit-toggle">
                  <button class="active">Imperial System</button>
                  <button>Metric System</button>
                </div>
              </div>
              <ul class="ingredients-list">
                ${data.ingredients.map((ing) => `
                  <li>
                    <span class="ingredient-bullet"></span>
                    <span class="ingredient-text">
                      ${ing.amount ? `<span class="ingredient-amount">${ing.amount}</span> ` : ''}${ing.name || ing}
                    </span>
                  </li>
                `).join('')}
              </ul>
            </div>
          ` : ''}

          <div class="recipe-section directions-section">
            <h2>Directions</h2>
            <ol class="directions-list">
              ${data.steps && data.steps.length > 0 ? data.steps.map((step, i) => `
                <li>
                  <span class="step-number">${i + 1}</span>
                  <div class="step-content">
                    <p class="step-instruction">${step.instruction || step}</p>
                    ${step.tip ? `
                      <div class="step-tip">
                        <span class="tip-icon">i</span>
                        <span>${step.tip}</span>
                      </div>
                    ` : ''}
                  </div>
                </li>
              `).join('') : '<li>No instructions available</li>'}
            </ol>
          </div>

          ${data.chef_notes ? `
            <div class="recipe-section chef-notes-section">
              <h2>Chef's Notes</h2>
              <p>${data.chef_notes}</p>
            </div>
          ` : ''}
        </div>
      </div>

      ${data.related_recipes && data.related_recipes.length > 0 ? `
        <div class="recipe-section related-recipes-section">
          <h2>You Might Also Like</h2>
          <div class="related-grid">
            ${data.related_recipes.map((r) => `
              <div class="related-recipe" data-query="${r.query || r.name}">
                <div class="related-image">
                  <img src="${r.image_url || '/icons/placeholder.svg'}" alt="${r.name}">
                </div>
                <h3>${r.name}</h3>
                ${r.description ? `<p>${r.description}</p>` : ''}
              </div>
            `).join('')}
          </div>
        </div>
      ` : ''}
    </div>
  `;

  block.innerHTML = html;

  // Add click handlers for related recipes
  setupRelatedRecipeLinks(block);

  // Setup tab functionality
  setupTabs(block);
}

/**
 * Setup click handlers for related recipe cards
 */
function setupRelatedRecipeLinks(block) {
  const relatedCards = block.querySelectorAll('.related-recipe');
  relatedCards.forEach((card) => {
    card.addEventListener('click', () => {
      const query = card.dataset.query;
      if (query) {
        // Navigate to generate new recipe page
        const event = new CustomEvent('adaptive-navigate', {
          detail: { mode: 'generate', query },
        });
        window.dispatchEvent(event);
        // Update URL
        const url = new URL(window.location);
        url.searchParams.set('q', query);
        url.searchParams.delete('id');
        window.history.pushState({}, '', url);
      }
    });
  });
}

/**
 * Setup tab switching functionality
 */
function setupTabs(block) {
  const tabs = block.querySelectorAll('.recipe-tab');
  tabs.forEach((tab) => {
    tab.addEventListener('click', () => {
      // Remove active from all tabs
      tabs.forEach((t) => t.classList.remove('active'));
      // Add active to clicked tab
      tab.classList.add('active');
      // In a full implementation, this would switch content sections
    });
  });
}
