-- Auto-generated video seed data from Vitamix YouTube channel

INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('wGdk2Du4eqE', 'Meet the Ascent X5', 'Introducing the Vitamix Ascent X5 - our premium blender with 10 blending programs, touch interface, and Self-Detect technology.', 'https://i.ytimg.com/vi/wGdk2Du4eqE/hqdefault.jpg', 90, '2025-02-01T10:00:00Z', 9000, 450, '["product","ascent-x","introduction"]', '["ascent-x5"]', '[]', '["ascent x5","vitamix","blender","premium blender"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('ysvdMRI1zIw', 'Meet the Ascent X4', 'Discover the Vitamix Ascent X4 with 4 blending programs, touch interface, and premium features.', 'https://i.ytimg.com/vi/ysvdMRI1zIw/hqdefault.jpg', 85, '2025-02-01T10:00:00Z', 3300, 165, '["product","ascent-x","introduction"]', '["ascent-x4"]', '[]', '["ascent x4","vitamix","blender"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('MzQsa_JYBRo', 'Meet the Ascent X3', 'Introducing the Vitamix Ascent X3 with 3 blending programs and touch interface.', 'https://i.ytimg.com/vi/MzQsa_JYBRo/hqdefault.jpg', 80, '2025-02-01T10:00:00Z', 2200, 110, '["product","ascent-x","introduction"]', '["ascent-x3"]', '[]', '["ascent x3","vitamix","blender"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('dGhKHXzkREg', 'Meet the Ascent X2', 'Discover the Vitamix Ascent X2 - entry-level Ascent X with Self-Detect technology.', 'https://i.ytimg.com/vi/dGhKHXzkREg/hqdefault.jpg', 81, '2025-02-01T10:00:00Z', 3700, 185, '["product","ascent-x","introduction"]', '["ascent-x2"]', '[]', '["ascent x2","vitamix","blender","entry level"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('bn3yWtKAFYs', 'Vitamix Ascent X2 SmartPrep Kitchen System', 'The complete Ascent X2 SmartPrep Kitchen System with food processor and blending accessories.', 'https://i.ytimg.com/vi/bn3yWtKAFYs/hqdefault.jpg', 57, '2025-06-01T14:00:00Z', 2600, 130, '["product","ascent-x","smartprep"]', '["ascent-x2-smartprep"]', '[]', '["smartprep","kitchen system","ascent x2","vitamix"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('Yd91DHGm6H8', 'Vitamix Ascent X4 Gourmet SmartPrep Kitchen System', 'Premium kitchen system with Ascent X4, food processor, and gourmet accessories.', 'https://i.ytimg.com/vi/Yd91DHGm6H8/hqdefault.jpg', 59, '2025-06-01T14:00:00Z', 1400, 70, '["product","ascent-x","smartprep"]', '["ascent-x4-gourmet-smartprep"]', '[]', '["smartprep","gourmet","kitchen system","ascent x4"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('m-FehBFidAc', 'Ascent X Series: Try Everything', 'Experience the full potential of the Vitamix Ascent X Series - smoothies, soups, nut butters, and more.', 'https://i.ytimg.com/vi/m-FehBFidAc/hqdefault.jpg', 31, '2025-01-01T15:00:00Z', 9400, 470, '["product","ascent-x","overview"]', '["ascent-x5","ascent-x4","ascent-x3","ascent-x2"]', '["green-smoothie","tomato-basil-soup","almond-butter"]', '["ascent x series","vitamix","blender comparison"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('7Lc7o3Y5DkM', 'The Essential Cocktail', 'Make the perfect frozen cocktail with your Vitamix blender.', 'https://i.ytimg.com/vi/7Lc7o3Y5DkM/hqdefault.jpg', 16, '2025-09-01T16:00:00Z', 996000, 49800, '["recipe","cocktail","frozen-drink"]', '["ascent-x5","propel-750"]', '["whole-fruit-margarita"]', '["cocktail","frozen drinks","margarita","vitamix recipe"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('ycDmkH2ETU0', 'Vitamix: Only the Essential', 'Discover what makes Vitamix the essential kitchen tool for healthy living.', 'https://i.ytimg.com/vi/ycDmkH2ETU0/hqdefault.jpg', 31, '2025-08-01T10:00:00Z', 975000, 48750, '["brand","lifestyle","overview"]', '[]', '[]', '["vitamix","healthy living","brand story"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('N3whSx-5VoU', 'Vitamix Personal Cup Adapter', 'Make single-serve smoothies and blends with the Personal Cup Adapter accessory.', 'https://i.ytimg.com/vi/N3whSx-5VoU/hqdefault.jpg', 61, '2025-09-01T10:00:00Z', 1900, 95, '["accessory","product","tutorial"]', '["propel-750","e310"]', '["green-smoothie"]', '["personal cup","adapter","single serve","accessory"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('AOjE_B-bcHU', 'Culinary Connections: Vichyssoise (Potato Leek Soup) by Chef Eric Wells', 'Learn to make classic French Vichyssoise potato leek soup with Chef Eric Wells using your Vitamix.', 'https://i.ytimg.com/vi/AOjE_B-bcHU/hqdefault.jpg', 420, '2025-09-01T12:00:00Z', 559, 28, '["recipe","soup","chef-series"]', '["ascent-x5"]', '[]', '["vichyssoise","potato soup","leek soup","chef recipe","french cuisine"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('ZnERDGw40EA', 'Vitamix 12-Cup Food Processor Attachment with SELF-DETECT', 'Expand your Vitamix with the 12-Cup Food Processor Attachment featuring SELF-DETECT technology.', 'https://i.ytimg.com/vi/ZnERDGw40EA/hqdefault.jpg', 83, '2025-05-01T14:00:00Z', 5400, 270, '["accessory","product","food-processor"]', '["ascent-x5","ascent-x4"]', '[]', '["food processor","self-detect","attachment","accessory"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('-QwPScX1TEY', 'Culinary Connections: Mushroom Bulgogi Mia and Khana', 'Create delicious mushroom bulgogi with Mia and Khana using your Vitamix.', 'https://i.ytimg.com/vi/-QwPScX1TEY/hqdefault.jpg', 683, '2025-06-01T12:00:00Z', 707, 35, '["recipe","korean","chef-series"]', '["ascent-x5"]', '[]', '["bulgogi","mushroom","korean food","chef recipe"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('CqfCfyktCDA', 'Quick & Quiet Recipe: Mango Smoothie', 'Make a delicious mango smoothie using the Quick & Quiet blending feature.', 'https://i.ytimg.com/vi/CqfCfyktCDA/hqdefault.jpg', 86, '2025-01-01T11:00:00Z', 2100, 105, '["recipe","smoothie","tutorial"]', '["ascent-x5","ascent-x4"]', '[]', '["mango smoothie","quick and quiet","smoothie recipe"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('D0SzzVyTMVY', 'Quick & Quiet Recipe: Caramel Frappe', 'Create a coffee shop-style caramel frappe at home with the Quick & Quiet feature.', 'https://i.ytimg.com/vi/D0SzzVyTMVY/hqdefault.jpg', 66, '2025-01-01T11:00:00Z', 4400, 220, '["recipe","coffee","frappe"]', '["ascent-x5","ascent-x4"]', '[]', '["caramel frappe","coffee","iced coffee","quick and quiet"]');
INSERT OR REPLACE INTO videos (id, title, description, thumbnail_url, duration_seconds, published_at, view_count, like_count, categories, products_mentioned, recipes_mentioned, tags) VALUES ('OzlmHdIokOU', 'Immersi-Prep: Roasted Red Pepper Soup', 'Make creamy roasted red pepper soup using the Immersi-Prep immersion blender.', 'https://i.ytimg.com/vi/OzlmHdIokOU/hqdefault.jpg', 115, '2025-01-01T12:00:00Z', 592, 30, '["recipe","soup","immersion-blender"]', '[]', '["roasted-red-pepper-soup"]', '["roasted red pepper","soup","immersion blender","immersi-prep"]');

